apiVersion: apps/v1
kind: Deployment
metadata:
  name: enddeviceservice
  labels:
    name: enddeviceservice
  namespace: avionicscloud
spec:
  replicas: 1
  selector:
    matchLabels:
      name: enddeviceservice
  template:
    metadata:
      labels: 
       name: enddeviceservice
    spec:
      containers:
      - name: enddeviceservice
        image: avionicscloud/enddeviceservice:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: RedisIp
            value: "172.18.67.183"
        ports:
        - containerPort: 6100
---
apiVersion: v1
kind: Service
metadata:
  name: enddeviceservice
  labels: 
   name: enddeviceservice
  namespace: avionicscloud
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 6100
  selector:
    name: enddeviceservice
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ui
    labels:
      name: ui
    namespace: avionicscloud
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: ui
    template:
      metadata:
        labels: 
         name: ui
      spec:
        containers:
        - name: ui
          image: avionicscloud/ui:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels: 
    name: ui
  namespace: avionicscloud
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31080
  selector:
    name: ui